--테이블 생성 부분
--===========================================================================
CREATE TABLE MEMBER_TB(
	USER_ID VARCHAR2(100 CHAR) PRIMARY KEY,
	USER_PW VARCHAR2(20) CHECK(LENGTH(USER_PW) > 3),
	USER_NAME VARCHAR2(15) NOT NULL,
	USER_JUMIN CHAR(13) NOT NULL UNIQUE,
  	USER_NICK VARCHAR2(36) NOT NULL,
  	USER_PHONE CHAR(11) NOT NULL UNIQUE,
  	USER_ADDRESS VARCHAR2(150) NOT NULL
);


CREATE TABLE ALCOHOL_TB(
    ALCOHOL_NAME VARCHAR2(100) PRIMARY KEY,
    CATEGORY VARCHAR2(20) NOT NULL,
    COUNTRY_OF_ORIGIN VARCHAR2(50),
    COM VARCHAR2(100),
    ABV NUMBER(4,2),
    VOLUME NUMBER(4),
    PRICE NUMBER(7),
    TAG VARCHAR2(255)
);

CREATE TABLE REVIEW_TB (
	USER_ID VARCHAR2(20) REFERENCES MEMBER_TB(USER_ID) ,
	ALCOHOL_NAME VARCHAR2(100) REFERENCES ALCOHOL_TB(ALCOHOL_NAME),
	REVIEW VARCHAR(255) NOT NULL
);


CREATE TABLE SCORE_TB (
	USER_ID VARCHAR2(20) REFERENCES MEMBER_TB(USER_ID) ,
	ALCOHOL_NAME VARCHAR2(100) REFERENCES ALCOHOL_TB(ALCOHOL_NAME),    
	SCORE NUMBER(2,1) NOT NULL
);


CREATE TABLE JJIM_TB (
	USER_ID VARCHAR2(20) REFERENCES MEMBER_TB(USER_ID) ,
	ALCOHOL_NAME VARCHAR2(100) REFERENCES ALCOHOL_TB(ALCOHOL_NAME),
	JJIM NUMBER(1) NOT NULL
);


--데이터 입력
--===========================================================================
--회원 데이터 추가
INSERT ALL 
INTO MEMBER_TB(USER_ID, USER_PW, USER_NAME, USER_JUMIN, USER_NICK, USER_PHONE, USER_ADDRESS) 
VALUES('user1@naver.com', 12345671,'이경섭',9403101511111,'스누피누피',01012341234,'서울특별시 용산구 청파동')
INTO MEMBER_TB(USER_ID, USER_PW, USER_NAME, USER_JUMIN, USER_NICK, USER_PHONE, USER_ADDRESS) 
VALUES('user2@naver.com', 12345672,'강인구',9403101522222,'강한남자강인구',01012344321,'광주광역시 광산구 산월동')
INTO MEMBER_TB(USER_ID, USER_PW, USER_NAME, USER_JUMIN, USER_NICK, USER_PHONE, USER_ADDRESS) 
VALUES('user3@naver.com', 12345673,'김세호',9403101533333,'노래방싫헝',01012341111,'경기도 이천시')
INTO MEMBER_TB(USER_ID, USER_PW, USER_NAME, USER_JUMIN, USER_NICK, USER_PHONE, USER_ADDRESS) 
VALUES('user4@naver.com', 12345674,'박성진',9403101544444,'먹방의신',01012341222,'경기도 수원시')
INTO MEMBER_TB(USER_ID, USER_PW, USER_NAME, USER_JUMIN, USER_NICK, USER_PHONE, USER_ADDRESS) 
VALUES('user5@naver.com', 12345675,'서용욱',9403101555555,'이세카이아이돌',01012340231,'서울특별시 강남구 서초동')
SELECT * FROM DUAL;

--술 데이터는 CSV파일로 추가

--리뷰 데이터 추가
INSERT ALL 
INTO REVIEW_TB(USER_ID, ALCOHOL_NAME,REVIEW) 
VALUES('user1@naver.com','입장탁주','먹어보니 맛이 아주 좋고 목넘김이 부드럽습니다.' )
INTO REVIEW_TB(USER_ID, ALCOHOL_NAME,REVIEW) 
VALUES('user2@naver.com','조니워커 블루','조니워커 그린이 맛있어서 블루도 먹어봤는데 생각보다 쓰고 맛없네요ㅠㅠ' )
INTO REVIEW_TB(USER_ID, ALCOHOL_NAME,REVIEW) 
VALUES('user3@naver.com','잭 다니엘스','항상 맛있어서 애용하고 있고 가성비 갑!!' )
INTO REVIEW_TB(USER_ID, ALCOHOL_NAME,REVIEW) 
VALUES('user4@naver.com','아잉거 알트 바이리쉬 둔켈','이거 매니아층만 아는 숨겨진 맛술~ 기름진 음식이랑 먹으면 짱짱~!!' )
INTO REVIEW_TB(USER_ID, ALCOHOL_NAME,REVIEW) 
VALUES('user5@naver.com','칭따오 병','치킨이랑 먹음 맛있당' )
SELECT * FROM DUAL;


--별점 데이터 추가
INSERT ALL 
INTO SCORE_TB(USER_ID, ALCOHOL_NAME,SCORE) 
VALUES('user1@naver.com','입장탁주',5 )
INTO SCORE_TB(USER_ID, ALCOHOL_NAME,SCORE) 
VALUES('user2@naver.com','조니워커 블루',4 )
INTO SCORE_TB(USER_ID, ALCOHOL_NAME,SCORE) 
VALUES('user3@naver.com','잭 다니엘스',4 )
INTO SCORE_TB(USER_ID, ALCOHOL_NAME,SCORE) 
VALUES('user4@naver.com','아잉거 알트 바이리쉬 둔켈',5 )
INTO SCORE_TB(USER_ID, ALCOHOL_NAME,SCORE) 
VALUES('user5@naver.com','칭따오 병',2 )
SELECT * FROM DUAL;

--찜 데이터 추가
INSERT ALL 
INTO JJIM_TB(USER_ID, ALCOHOL_NAME,JJIM) 
VALUES('user1@naver.com','입장탁주',1 )
INTO JJIM_TB(USER_ID, ALCOHOL_NAME,JJIM) 
VALUES('user2@naver.com','조니워커 블루',1 )
INTO JJIM_TB(USER_ID, ALCOHOL_NAME,JJIM) 
VALUES('user3@naver.com','잭 다니엘스',1 )
INTO JJIM_TB(USER_ID, ALCOHOL_NAME,JJIM) 
VALUES('user4@naver.com','아잉거 알트 바이리쉬 둔켈',1 )
INTO JJIM_TB(USER_ID, ALCOHOL_NAME,JJIM) 
VALUES('user5@naver.com','칭따오 병',1 )
SELECT * FROM DUAL;


--데이터 추가확인

SELECT * FROM MEMBER_TB;
SELECT * FROM ALCOHOL_TB;
SELECT * FROM REVIEW_TB;
SELECT * FROM SCORE_TB;
SELECT * FROM JJIM_TB;

--테이블 삭제
DROP TABLE MEMBER_TB CASCADE CONSTRAINTS;
DROP TABLE ALCOHOL_TB CASCADE CONSTRAINTS;
DROP TABLE REVIEW_TB CASCADE CONSTRAINTS;
DROP TABLE SCORE_TB CASCADE CONSTRAINTS;
DROP TABLE JJIM_TB CASCADE CONSTRAINTS;

--테이블 데이터 삭제
TRUNCATE TABLE MEMBER_TB;
TRUNCATE TABLE ALCOHOL_TB;
TRUNCATE TABLE REVIEW_TB;
TRUNCATE TABLE SCORE_TB;
TRUNCATE TABLE JJIM_TB;
